config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_attached_file :image, styles: { medium: "500x500>", small: "250x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   protect_from_forgery with: :exception
#
#   def configure_permitted_parameters
#   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email) }
# end
# end


class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,        keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :current_user, only: [:edit, :update, :destroy]

  # GET
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET
  def show
    @post = Post.find params[:id]
  end

  # GET
  def new
    @post = current_user.posts.build
  end

  # POST
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  # DELETE
  def destroy
    @post.destroy
    redirect_to root_path
  end

private

  # GET
  def edit
  end

  # PATCH
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
  end
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <%= render 'partials/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
    <ul>
      <li class="active"><%= link_to "#WATERLUST", root_path %></li>
      <li><a href="#shots">Shots</a></li>
      <li><a href="#about">About</a></li>
      <li><a href="#support">Support</a></li>
      <div id="signups">
        <li><%= link_to "Sign Up", new_user_session_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Log Out", destroy_user_session_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        <input class="search" type="text" name="search" placeholder="Search">
    </ul>
  #WATERLUST ©2017
</footer>

app/views/partials/_navbar.html.erb
<header>
  <title>#WATERLUST</title>
  <div class="nav">
  <ul>
    <li class="active"><%= link_to "#WATERLUST", root_path %></li>
    <li><a href="#shots">Shots</a></li>
    <li><a href="#about">About</a></li>
    <li><a href="#support">Support</a></li>
    <div id="signups">
      <li><%= link_to "Sign Up", new_user_session_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <input class="search" type="text" name="search" placeholder="Search">
  </ul>
  <ul class="subnav">
      <li><a href="#popular">Popular</a></li>
      <li><a href="#vote">Vote</a></li>
      <li id="upload"><%= link_to "Upload", new_post_path %></li>
  </ul>
</header>

app/views/posts/_form.html.erb
<div class="form">
<%= simple_form_for @post do |f| %>
  <%= f.input :image %>
  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>EDIT POST</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each_slice(4) do |row| %>
  <div class="row">
    <% row.each do |post| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to(image_tag(post.image.url :small), post_path(post)) %>
          </div>
          <div class="name">
            <%= link_to image_tag("icon.png") %>
            <%= link_to post.user.name %>
          </div>
          <div class="caption">
            <span class="glyphicon glyphicon-heart" aria-hidden="true">11</span>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true">17</span>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>#WATERLUST</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>
<p><%= image_tag @post.image.url(:medium) %><p>
  <div class="glyphs">
  <span class="glyphicon glyphicon-heart" aria-hidden="true">11</span>
  <span class="glyphicon glyphicon-eye-open" aria-hidden="true">17</span>
  </div>
<p><%= @post.link %></p>
<p><%= link_to image_tag("icon.png") %><%= @post.user.name %></p>

<% if @post.user == current_user %>
<p><%= link_to "Edit", edit_post_path(@post) %></p>
<p><%= link_to "Delete", post_path(@post), method: :delete %></p>
<% end %>